List transformers = [
  {"name": 'bumblebee'},
  {"name": "laser_optimus_prime"},
  {"name": "optimus-prime"},
  {"name": "arcee"},
  {"name": "breakdown_prime"},
  {"name": "optimus_primal (1)"},
  {"name": "cliffjumper"},
  {"name": "cybertron_starscream"},
  {"name": "goldfire"},
  {"name": "slipstream"},
];
List girls = [
  {"static_name": "","action_name":"hero_alice_divine_owl_lobby"},
  {"static_name": "","action_name":"hero_alice_lobby"},
  {"static_name": "","action_name":"hero_esmeralda_lobby"},
  {"static_name": "","action_name":"hero_guinevere_athena_asamiya_lobby"},
  {"static_name": "","action_name":"hero_guinevere_lobby"},
  {"static_name": "","action_name":"hero_guinevere_lotus_lobby"},
  {"static_name": "","action_name":"hero_hanabi_lobby"},
  {"static_name": "","action_name":"hero_kagura_lobby"},
  {"static_name": "","action_name":"hero_layla_lobby"},
  {"static_name": "","action_name":"hero_miya_lobby_2017"},
  {"static_name": "","action_name":"hero_rafaela_lobby"},
];
